@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ConceitosManualController
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/home

### ConceitosAutomaticoController
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico

### RecadosController
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "texto": "recado de teste",
    "de": "Felipe Muchulski",
    "para": "Lilian Borsoi"
}

### 
# Patch
PATCH {{baseUrl}}/recados/1771357261850/
Content-Type: application/json

{
    "texto": "Este é o novo recado"
}

### QueryParams na rota
GET {{baseUrl}}/recados/
?limit=10
&offset=10
&user=luiz


### findall
GET {{baseUrl}}/recados/all_recados
