@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ConceitosManualController
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/home

### ConceitosAutomaticoController
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico