@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

### ConceitosManualController
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/home

### ConceitosAutomaticoController
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico

### RecadosController
POST {{baseUrl}}/recados
Content-Type: application/json

{
    "recado": "recado de teste",
    "autor": "Felipe Muchulski"
}

### 
# Patch
PATCH {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "recado": "Este é o novo recado",
    "atualizar": "teste"
}
